# Site settings
title: Kristian Brevik
email: kristianbrevik@gmail.com
url: https://kbrevs.github.io
description: "Transposable Elements, Epigenetics, Genomes... Science!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/KristianBrevik
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: https://github.com/kbrevs

# Build settings
markdown: kramdown
permalink: pretty
